MainWindow: replace stack with Deck
elementary/installer pull request #635
Opened 2021-12-20 00:02 UTC by danrabbit

This makes a couple of assumptions that need to be verified:

- [ ] It's always okay to go back except on progress view. We may want to either disable navigation or make corrections on some pages.
- [ ] navigation is always linear. It's possible the old code set something as `previous_view` that wasn't actually the previous view. We should make sure views self-destruct if they can't be returned to after navigating away.
- [ ] Every child is an `AbstractInstallerView`. If any aren't, they'll need additional margins

2023-07-28 15:12 UTC, lenemter reviewed
Transition from CheckView to DisckView or PartitioningView is not so smooth because of removing CheckView. As a solution we can just keep it, or remove only when the next view is opened.

2023-08-01 17:49 UTC, lenemter commented on src/MainWindow.vala
> +        deck.can_swipe_back = true;
This should be false? Otherwise it is possible to swipe back to progress view and further back.

2023-08-01 17:57 UTC, lenemter requested changes
When pressing "Try Installing Again" button in ErrorView it navigates back to a progress view, where you can't do anything.

2023-08-01 18:04 UTC, danirabbit commented
@lenemter ah yep. It looks like previously it would send you back to the disks view, but I'm now having it send you back to the try/install view since you could have gotten there from the custom partitioning path as well

2023-08-01 18:13 UTC, lenemter commented on src/MainWindow.vala
> +        });
```suggestion
        error_view.retry_install.connect (() => {
            deck.visible_child = try_install_view;
             deck.can_swipe_back = true;
        });
```

2023-08-01 18:27 UTC, danirabbit commented on src/MainWindow.vala
> +        });
Good call!

2023-08-01 18:38 UTC, lenemter approved these changes

2023-08-01 18:39 UTC, merged