MainWindow: throw an infobar on battery
elementary/installer pull request #648
Opened 2022-04-30 18:35 UTC by danrabbit

Currently, if you go from powered to battery we throw you from wherever you were into the CheckView to warn you about installing on battery power. This branch throws an infobar covering the beginning of the action area instead.

The reasoning behind the placement here is to making sure you can still complete the language view if this is shown on startup. Another alternative would be waiting to throw the infobar until after you've completed the language view and then we could show it in the more traditional top aligned location

![Screenshot from 2022-04-30 11 15 37](https://user-images.githubusercontent.com/7277719/166118191-473f8240-1b6e-465b-b2a9-25ef600fbb3c.png)

2022-05-01 09:16 UTC, tintou requested changes
You need to listen to the selected language and reset the label on language selection so that it is translated in the language the user has chosen

2022-05-04 22:39 UTC, danrabbit commented
@tintou would setting it again like this work or do I need to destroy and rebuild the label?

2022-05-10 16:18 UTC, tintou commented
@danrabbit no this won't work, the `_()` function has to be called again so you need to regenerate the string

2022-05-10 16:50 UTC, danrabbit commented
@tintou okay I believe it's fixed now

2022-05-10 16:51 UTC, tintou approved these changes

2022-05-10 17:03 UTC, merged